### PR TITLE
pagination

### PR DESCRIPTION
**Pull request by krmeet**

### CODE REVIEW

**Comment by ezist** [comment]
I think Typical would be mad over your usage of '$stmt1' or whatever, but it works; so it's merge time.

**Comment by krmeet** [comment]
whats wrong with that lol

**Comment by ezist** [comment]
I dunno. He gets mad over things.

**Comment by typicalname0** [comment]
shut up fatty fat fat

**Comment by ezist** [comment]
>Mature developer
>"shut up fatty fat fat"

**Pull request merged**
